PLUGIN_TYPE_DATASETS = "datasets"
PLUGIN_TYPE_IDENTIFIERS = "identifiers"
PLUGIN_TYPE_TRANSFORMATION = "transformation"
PLUGIN_TYPE_AUGMENTATION = "augmentation"
PLUGIN_TYPE_EXPORT = "export"

PLUGIN_TYPES = (
    PLUGIN_TYPE_DATASETS,
    PLUGIN_TYPE_IDENTIFIERS,
    PLUGIN_TYPE_TRANSFORMATION,
    PLUGIN_TYPE_AUGMENTATION,
    PLUGIN_TYPE_EXPORT,
)
